# -*- coding: utf-8 -*-
"""Aprendizaje_por_Refuerzo_SAE.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jLYoCcPS--ggQhF-31y25aBpD6WFAD0y
"""

# -*- coding: utf-8 -*-
"""
# APRENDIZAJE POR REFUERZO: CUADERNO MODULAR PEDAGÓGICO
## De los Fundamentos Matemáticos a las Implementaciones Avanzadas

Este cuaderno está diseñado para ser ejecutado en bloques modulares, permitiendo
una comprensión gradual y reflexiva de cada concepto antes de avanzar al siguiente.

**INSTRUCCIONES PEDAGÓGICAS:**
1. Ejecute cada módulo completamente antes de pasar al siguiente
2. Observe y analice las visualizaciones generadas
3. Reflexione sobre las métricas mostradas
4. Experimente modificando los hiperparámetros sugeridos
"""

# ============================================================================
# MÓDULO 1: CONFIGURACIÓN FUNDAMENTAL DEL ENTORNO
# ============================================================================

"""
## MÓDULO 1: ESTABLECIMIENTO DEL ECOSISTEMA COMPUTACIONAL

**OBJETIVO PEDAGÓGICO:**
Configurar el entorno computacional y verificar que todas las dependencias
funcionen correctamente. Este módulo establece las bases tecnológicas para
nuestros experimentos posteriores.

**CONCEPTOS CLAVE:**
- Gestión de dependencias en Python
- Compatibilidad entre versiones de bibliotecas
- Configuración de reproducibilidad experimental
"""

import subprocess
import sys
import warnings
warnings.filterwarnings('ignore')  # Suprime warnings menores para claridad pedagógica

def setup_reinforcement_learning_environment():
    """
    Configura el entorno computacional con manejo robusto de versiones.

    Esta función implementa un sistema de fallbacks que garantiza compatibilidad
    con diferentes configuraciones de Google Colab y versiones de bibliotecas.
    """
    print("🔧 MÓDULO 1: Configurando Entorno Computacional")
    print("=" * 50)

    # Paquetes fundamentales para aprendizaje por refuerzo
    core_packages = [
        'torch', 'torchvision', 'numpy', 'matplotlib',
        'collections-extended', 'pygame'
    ]

    print("📦 Instalando dependencias core...")
    for package in core_packages:
        try:
            subprocess.check_call([sys.executable, '-m', 'pip', 'install', package],
                                 stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
            print(f"   ✅ {package}")
        except subprocess.CalledProcessError:
            print(f"   ⚠️  {package} (ya instalado o error menor)")

    # Detección inteligente de Gym vs Gymnasium
    print("\n🎮 Configurando entornos de simulación...")
    try:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', 'gymnasium[classic_control]'],
                             stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        print("   ✅ Gymnasium (versión moderna)")
        gym_type = 'gymnasium'
    except subprocess.CalledProcessError:
        try:
            subprocess.check_call([sys.executable, '-m', 'pip', 'install', 'gym[classic_control]==0.21.0'],
                                 stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
            print("   ✅ OpenAI Gym (versión clásica)")
            gym_type = 'gym'
        except subprocess.CalledProcessError:
            print("   ❌ Error instalando entornos")
            gym_type = None

    print(f"\n🎯 Configuración completada exitosamente")
    print(f"   Tipo de entorno: {gym_type}")
    return gym_type

# Ejecutar configuración
gym_version = setup_reinforcement_learning_environment()

# ============================================================================
# MÓDULO 2: IMPORTACIONES Y CONFIGURACIÓN MATEMÁTICA
# ============================================================================

"""
## MÓDULO 2: FUNDAMENTOS MATEMÁTICOS Y CONFIGURACIÓN

**OBJETIVO PEDAGÓGICO:**
Establecer el marco matemático fundamental y configurar la reproducibilidad
experimental. Comprender la importancia de la aleatoriedad controlada en
experimentos de aprendizaje automático.

**CONCEPTOS CLAVE:**
- Reproducibilidad en experimentos de ML
- Configuración de bibliotecas científicas
- Detección de recursos computacionales
"""

print("\n🧮 MÓDULO 2: Configuración Matemática y Científica")
print("=" * 50)

import numpy as np
import matplotlib.pyplot as plt
import torch
import torch.nn as nn
import torch.optim as optim
import random
from collections import defaultdict, namedtuple, deque
from typing import Tuple, List, Dict, Optional, Union
import time

# Configuración de reproducibilidad experimental
RANDOM_SEED = 42
np.random.seed(RANDOM_SEED)
torch.manual_seed(RANDOM_SEED)
random.seed(RANDOM_SEED)

# Configuración de visualización optimizada
plt.style.use('default')  # Usar estilo por defecto para máxima compatibilidad
plt.rcParams['figure.figsize'] = (12, 8)
plt.rcParams['font.size'] = 11

# Detección de capacidades computacionales
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

print(f"🎲 Semilla aleatoria establecida: {RANDOM_SEED}")
print(f"🔢 Versión de PyTorch: {torch.__version__}")
print(f"💻 Dispositivo computacional: {device}")
print(f"🎨 Backend de visualización: {plt.get_backend()}")

print("\n✅ Módulo 2 completado - Fundamentos matemáticos establecidos")

# ============================================================================
# INSTRUCCIONES PARA EL INSTRUCTOR
# ============================================================================

print("\n" + "="*60)
print("📚 PAUSA PEDAGÓGICA - INSTRUCCIONES PARA EL INSTRUCTOR")
print("="*60)
print("""
En este punto, debe explicar a los estudiantes:

1. La importancia de la REPRODUCIBILIDAD en experimentos de ML
2. Por qué utilizamos semillas aleatorias fijas
3. Cómo la configuración del entorno afecta los resultados
4. La diferencia entre Gym y Gymnasium

PREGUNTAS PARA REFLEXIÓN:
- ¿Por qué es crucial la reproducibilidad en experimentos científicos?
- ¿Qué ventajas ofrece CUDA para el aprendizaje profundo?
- ¿Cómo afecta la versión de PyTorch a nuestros experimentos?

ACTIVIDAD SUGERIDA:
Hacer que los estudiantes cambien la semilla aleatoria y observen cómo
cambian los resultados en módulos posteriores.
""")
print("="*60)

# ============================================================================
# MÓDULO 3: PROCESOS DE DECISIÓN DE MARKOV - TEORÍA IMPLEMENTADA
# ============================================================================

"""
## MÓDULO 3: PROCESOS DE DECISIÓN DE MARKOV (MDPs)

**OBJETIVO PEDAGÓGICO:**
Implementar y visualizar los conceptos fundamentales de MDPs. Comprender
cómo la ecuación de Bellman establece la base matemática para todos los
algoritmos de aprendizaje por refuerzo.

**CONCEPTOS CLAVE:**
- Definición formal de MDP: ⟨S, A, P, R, γ⟩
- Ecuación de Bellman para evaluación de políticas
- Convergencia iterativa de funciones de valor
"""

print("\n🏗️  MÓDULO 3: Procesos de Decisión de Markov")
print("=" * 50)

class MDPEducativo:
    """
    Implementación pedagógica de un MDP que revela la estructura matemática
    subyacente de manera explícita y comprensible.
    """

    def __init__(self, n_estados: int, n_acciones: int, gamma: float = 0.9):
        """
        Inicializa un MDP con los componentes fundamentales.

        Args:
            n_estados: |S| - Cardinalidad del espacio de estados
            n_acciones: |A| - Cardinalidad del espacio de acciones
            gamma: Factor de descuento γ ∈ [0,1]
        """
        self.S = n_estados
        self.A = n_acciones
        self.gamma = gamma

        # Inicialización de las funciones de transición y recompensa
        # P(s'|s,a) - Probabilidades de transición
        self.P = np.zeros((n_estados, n_acciones, n_estados))
        # R(s,a,s') - Función de recompensa
        self.R = np.zeros((n_estados, n_acciones, n_estados))

        print(f"🎯 MDP creado exitosamente:")
        print(f"   Estados (|S|): {n_estados}")
        print(f"   Acciones (|A|): {n_acciones}")
        print(f"   Factor de descuento (γ): {gamma}")

    def ecuacion_bellman(self, politica: np.ndarray, funcion_valor: np.ndarray) -> np.ndarray:
        """
        Implementa la ecuación de Bellman para evaluación de políticas.

        Ecuación: v^π(s) = Σ_a π(a|s) Σ_{s'} P(s'|s,a)[R(s,a,s') + γv^π(s')]

        Args:
            politica: π(a|s) - Matriz de política [S×A]
            funcion_valor: v^π(s) - Vector de función de valor [S]

        Returns:
            Nueva función de valor actualizada según Bellman
        """
        nueva_v = np.zeros(self.S)

        for estado in range(self.S):
            valor_estado = 0.0

            # Sumar sobre todas las acciones ponderadas por la política
            for accion in range(self.A):
                prob_accion = politica[estado, accion]
                valor_accion = 0.0

                # Sumar sobre todos los estados siguientes
                for siguiente_estado in range(self.S):
                    prob_transicion = self.P[estado, accion, siguiente_estado]
                    recompensa = self.R[estado, accion, siguiente_estado]
                    valor_futuro = self.gamma * funcion_valor[siguiente_estado]

                    valor_accion += prob_transicion * (recompensa + valor_futuro)

                valor_estado += prob_accion * valor_accion

            nueva_v[estado] = valor_estado

        return nueva_v

# Crear un MDP de demostración pedagógica
print("\n📊 DEMOSTRACIÓN: Evaluación de Políticas con Bellman")
mdp_demo = MDPEducativo(n_estados=3, n_acciones=2, gamma=0.9)

# Configurar dinámicas de transición determinísticas para claridad conceptual
mdp_demo.P[0, 0, 1] = 1.0  # Desde estado 0, acción 0 → estado 1 (probabilidad 1)
mdp_demo.P[0, 1, 2] = 1.0  # Desde estado 0, acción 1 → estado 2 (probabilidad 1)
mdp_demo.P[1, 0, 0] = 1.0  # Desde estado 1, acción 0 → estado 0 (ciclo)
mdp_demo.P[1, 1, 2] = 1.0  # Desde estado 1, acción 1 → estado 2 (terminal)
mdp_demo.P[2, :, 2] = 1.0  # Estado 2 es absorbente (terminal)

# Configurar recompensas estratégicamente
mdp_demo.R[1, 1, 2] = 1.0  # Recompensa por transición exitosa al estado terminal

# Definir política equiprobable para análisis
politica_uniforme = np.ones((3, 2)) * 0.5
print(f"Política bajo análisis: Equiprobable π(a|s) = 0.5 ∀s,a")

# Evaluación iterativa de la política
funcion_v = np.zeros(3)
print(f"\nIteración | V(s₀)   | V(s₁)   | V(s₂)   | Δ_max")
print("-" * 50)

for iteracion in range(15):
    v_anterior = funcion_v.copy()
    funcion_v = mdp_demo.ecuacion_bellman(politica_uniforme, funcion_v)
    delta_max = np.max(np.abs(funcion_v - v_anterior))

    if iteracion % 3 == 0:  # Mostrar cada 3 iteraciones para claridad
        print(f"   {iteracion:2d}     | {funcion_v[0]:.4f} | {funcion_v[1]:.4f} | {funcion_v[2]:.4f} | {delta_max:.6f}")

print(f"\n🎯 Convergencia alcanzada - Función de valor estabilizada")
print(f"   Interpretación: V(s₀)={funcion_v[0]:.4f} representa el valor esperado")
print(f"   de comenzar en el estado 0 y seguir la política equiprobable")

print("\n✅ Módulo 3 completado - Fundamentos de MDP establecidos")

# ============================================================================
# PAUSA PEDAGÓGICA 2
# ============================================================================

print("\n" + "="*60)
print("📚 PAUSA PEDAGÓGICA - ANÁLISIS DE LA ECUACIÓN DE BELLMAN")
print("="*60)
print("""
PUNTOS CLAVE PARA DISCUSIÓN:

1. INTERPRETACIÓN MATEMÁTICA:
   - V(s₀) ≈ 0.281 significa que comenzar en estado 0 tiene valor esperado 0.281
   - La convergencia demuestra que la ecuación de Bellman tiene punto fijo único
   - γ = 0.9 descuenta las recompensas futuras apropiadamente

2. OBSERVACIONES ALGORÍTMICAS:
   - La iteración converge geométricamente (propiedad de contracción)
   - El estado terminal V(s₂) = 0 como es esperado
   - V(s₁) > V(s₀) porque s₁ está más cerca de la recompensa

EXPERIMENTO SUGERIDO:
Cambie el factor de descuento γ y observe cómo afecta los valores finales.
¿Qué sucede cuando γ → 0? ¿Y cuando γ → 1?
""")
print("="*60)

# ============================================================================
# MÓDULO 4: ENTORNO GRIDWORLD EDUCATIVO
# ============================================================================

"""
## MÓDULO 4: LABORATORIO VIRTUAL - ENTORNO GRIDWORLD

**OBJETIVO PEDAGÓGICO:**
Crear un entorno visual e intuitivo donde los conceptos abstractos de
aprendizaje por refuerzo se vuelven tangibles y observables.

**CONCEPTOS CLAVE:**
- Mapeo entre estados abstractos y representaciones espaciales
- Diseño de funciones de recompensa
- Estados terminales y dinámicas de transición
"""

print("\n🌐 MÓDULO 4: Entorno GridWorld Educativo")
print("=" * 50)

import matplotlib.patches as patches

class GridWorldEducativo:
    """
    Entorno GridWorld diseñado específicamente para enseñanza, con
    visualizaciones claras y métricas pedagógicas integradas.
    """

    def __init__(self, altura: int = 5, ancho: int = 6):
        """
        Inicializa el entorno GridWorld con configuración pedagógica optimizada.

        Args:
            altura: Número de filas en la grilla
            ancho: Número de columnas en la grilla
        """
        self.altura = altura
        self.ancho = ancho
        self.n_estados = altura * ancho
        self.n_acciones = 4  # {Arriba, Derecha, Abajo, Izquierda}

        # Mapeo bidireccional entre coordenadas y estados
        self.estado_a_coord = {s: (s // ancho, s % ancho) for s in range(self.n_estados)}
        self.coord_a_estado = {coord: estado for estado, coord in self.estado_a_coord.items()}

        # Configuración de estados especiales con justificación pedagógica
        fila_objetivo, col_objetivo = altura // 2, ancho - 2
        self.estado_objetivo = self.coord_a_estado[(fila_objetivo, col_objetivo)]

        # Posicionamiento estratégico de trampas para crear dilemas interesantes
        posiciones_trampas = [
            (fila_objetivo + 1, col_objetivo),    # Sur del objetivo
            (fila_objetivo, col_objetivo - 1),    # Oeste del objetivo
            (fila_objetivo - 1, col_objetivo)     # Norte del objetivo
        ]

        self.estados_trampa = [self.coord_a_estado[pos] for pos in posiciones_trampas
                              if self._posicion_valida(*pos)]

        self.estados_terminales = {self.estado_objetivo} | set(self.estados_trampa)

        # Estado inicial y actual
        self.estado_inicial = 0
        self.estado_actual = self.estado_inicial

        # Definición de acciones con semántica clara
        self.acciones = {
            0: (-1, 0),  # Arriba
            1: (0, 1),   # Derecha
            2: (1, 0),   # Abajo
            3: (0, -1)   # Izquierda
        }

        self.nombres_acciones = ['↑', '→', '↓', '←']

        print(f"🏗️  GridWorld {altura}×{ancho} creado exitosamente")
        print(f"   📍 Objetivo: Estado {self.estado_objetivo} (coordenadas {self.estado_a_coord[self.estado_objetivo]})")
        print(f"   ⚠️  Trampas: Estados {self.estados_trampa}")
        print(f"   🏁 Estados terminales: {len(self.estados_terminales)}")
        print(f"   🎯 Espacio de estados: {self.n_estados}")
        print(f"   🎮 Espacio de acciones: {self.n_acciones}")

    def _posicion_valida(self, fila: int, col: int) -> bool:
        """Verifica si una posición está dentro de los límites."""
        return 0 <= fila < self.altura and 0 <= col < self.ancho

    def reset(self) -> int:
        """Reinicia el entorno al estado inicial."""
        self.estado_actual = self.estado_inicial
        return self.estado_actual

    def step(self, accion: int) -> Tuple[int, float, bool, dict]:
        """
        Ejecuta una acción y retorna la transición resultante.

        Args:
            accion: Índice de la acción {0: ↑, 1: →, 2: ↓, 3: ←}

        Returns:
            (próximo_estado, recompensa, terminado, info)
        """
        if self.estado_actual in self.estados_terminales:
            return self.estado_actual, 0.0, True, {}

        # Calcular posición resultante
        fila_actual, col_actual = self.estado_a_coord[self.estado_actual]
        delta_fila, delta_col = self.acciones[accion]
        nueva_fila, nueva_col = fila_actual + delta_fila, col_actual + delta_col

        # Aplicar restricciones de fronteras
        if not self._posicion_valida(nueva_fila, nueva_col):
            nueva_fila, nueva_col = fila_actual, col_actual

        # Actualizar estado
        self.estado_actual = self.coord_a_estado[(nueva_fila, nueva_col)]

        # Calcular recompensa con diseño pedagógico claro
        if self.estado_actual == self.estado_objetivo:
            recompensa = 1.0   # Recompensa positiva por éxito
        elif self.estado_actual in self.estados_trampa:
            recompensa = -1.0  # Penalización por fracaso
        else:
            recompensa = 0.0   # Movimiento neutral

        terminado = self.estado_actual in self.estados_terminales

        info = {
            'accion_nombre': self.nombres_acciones[accion],
            'coordenadas': self.estado_a_coord[self.estado_actual]
        }

        return self.estado_actual, recompensa, terminado, info

    def visualizar(self, politica: Optional[np.ndarray] = None,
                  funcion_valor: Optional[np.ndarray] = None,
                  titulo: str = "Estado Actual del GridWorld"):
        """
        Renderiza el estado actual con información opcional de política y valores.

        Args:
            politica: Política a visualizar (opcional)
            funcion_valor: Función de valor a mostrar (opcional)
            titulo: Título del gráfico
        """
        fig, ax = plt.subplots(1, 1, figsize=(10, 8))

        # Dibujar grilla base
        for i in range(self.altura + 1):
            ax.axhline(y=i, color='black', linewidth=0.5)
        for j in range(self.ancho + 1):
            ax.axvline(x=j, color='black', linewidth=0.5)

        # Colorear objetivo
        fila_obj, col_obj = self.estado_a_coord[self.estado_objetivo]
        rect_objetivo = patches.Rectangle((col_obj, self.altura - fila_obj - 1), 1, 1,
                                        linewidth=2, edgecolor='gold', facecolor='yellow', alpha=0.7)
        ax.add_patch(rect_objetivo)
        ax.text(col_obj + 0.5, self.altura - fila_obj - 0.5, '★',
                fontsize=20, ha='center', va='center', color='orange')

        # Dibujar trampas
        for estado_trampa in self.estados_trampa:
            fila_t, col_t = self.estado_a_coord[estado_trampa]
            rect_trampa = patches.Rectangle((col_t, self.altura - fila_t - 1), 1, 1,
                                          linewidth=2, edgecolor='red', facecolor='salmon', alpha=0.7)
            ax.add_patch(rect_trampa)
            ax.text(col_t + 0.5, self.altura - fila_t - 0.5, '✗',
                    fontsize=16, ha='center', va='center', color='darkred')

        # Dibujar agente actual
        fila_agente, col_agente = self.estado_a_coord[self.estado_actual]
        circulo_agente = patches.Circle((col_agente + 0.5, self.altura - fila_agente - 0.5),
                                      0.3, facecolor='blue', edgecolor='darkblue', linewidth=2)
        ax.add_patch(circulo_agente)

        # Mostrar función de valor si se proporciona
        if funcion_valor is not None:
            for estado in range(self.n_estados):
                fila, col = self.estado_a_coord[estado]
                if estado not in self.estados_terminales:
                    ax.text(col + 0.2, self.altura - fila - 0.8, f'{funcion_valor[estado]:.2f}',
                           fontsize=8, ha='center', va='center', color='purple', weight='bold')

        # Mostrar política si se proporciona
        if politica is not None:
            for estado in range(self.n_estados):
                if estado not in self.estados_terminales:
                    mejor_accion = np.argmax(politica[estado])
                    fila, col = self.estado_a_coord[estado]
                    ax.text(col + 0.8, self.altura - fila - 0.2, self.nombres_acciones[mejor_accion],
                           fontsize=12, ha='center', va='center', color='green', weight='bold')

        ax.set_xlim(0, self.ancho)
        ax.set_ylim(0, self.altura)
        ax.set_aspect('equal')
        ax.set_title(titulo, fontsize=14, weight='bold')
        ax.set_xlabel('Coordenada X')
        ax.set_ylabel('Coordenada Y')

        plt.tight_layout()
        plt.show()

# Crear y demostrar el entorno
print("\n🎯 CREANDO ENTORNO DE DEMOSTRACIÓN")
env_educativo = GridWorldEducativo(altura=5, ancho=6)
env_educativo.visualizar(titulo="GridWorld Inicial - Estados y Configuración")

# Simulación educativa de episodio aleatorio
print("\n🎲 SIMULACIÓN: Episodio con Política Aleatoria")
env_educativo.reset()
trayectoria_estados = [env_educativo.estado_actual]
trayectoria_recompensas = []

print(f"Estado inicial: {env_educativo.estado_actual} {env_educativo.estado_a_coord[env_educativo.estado_actual]}")

for paso in range(15):  # Límite para evitar bucles infinitos
    accion = np.random.randint(0, 4)
    siguiente_estado, recompensa, terminado, info = env_educativo.step(accion)

    trayectoria_estados.append(siguiente_estado)
    trayectoria_recompensas.append(recompensa)

    print(f"Paso {paso+1}: {info['accion_nombre']} → Estado {siguiente_estado} {info['coordenadas']}, R={recompensa}")

    if terminado:
        print(f"🏁 Episodio terminado en {paso+1} pasos")
        print(f"📊 Recompensa total: {sum(trayectoria_recompensas):.1f}")
        resultado = "ÉXITO" if recompensa > 0 else "FRACASO"
        print(f"🎯 Resultado: {resultado}")
        break

print("\n✅ Módulo 4 completado - Entorno GridWorld establecido")

# ============================================================================
# PAUSA PEDAGÓGICA 3
# ============================================================================

print("\n" + "="*60)
print("📚 PAUSA PEDAGÓGICA - ANÁLISIS DEL ENTORNO GRIDWORLD")
print("="*60)
print("""
CONCEPTOS FUNDAMENTALES OBSERVADOS:

1. DISEÑO DE RECOMPENSAS:
   - Objetivo (+1): Incentiva el comportamiento deseado
   - Trampas (-1): Penaliza errores y crea riesgo
   - Movimientos neutros (0): No sesgan la exploración

2. DINÁMICAS ESPACIALES:
   - Estados terminales crean episodios finitos
   - Restricciones de fronteras mantienen validez
   - Proximidad espacial afecta la dificultad del aprendizaje

3. INTERPRETACIÓN DE TRAYECTORIAS:
   - Política aleatoria muestra comportamiento de línea base
   - Longitud del episodio indica eficiencia
   - Patrón de movimientos revela estructura del problema

PREGUNTAS PARA REFLEXIÓN:
- ¿Cómo afecta la posición de las trampas al aprendizaje?
- ¿Qué estrategias podría desarrollar un agente inteligente?
- ¿Cómo cambiaría el problema con diferentes recompensas?
""")
print("="*60)

print("\n🎓 ¡Preparado para el siguiente módulo!")
print("En el próximo bloque implementaremos Q-Learning tabular...")

# ============================================================================
# MÓDULO 5: IMPLEMENTACIÓN DE Q-LEARNING TABULAR
# ============================================================================

"""
## MÓDULO 5: Q-LEARNING TABULAR - ALGORITMO FUNDAMENTAL

**OBJETIVO PEDAGÓGICO:**
Implementar el algoritmo Q-Learning paso a paso, comprendiendo cada componente
y observando cómo emerge el comportamiento inteligente desde la exploración aleatoria.

**CONCEPTOS CLAVE:**
- Regla de actualización Q(s,a) ← Q(s,a) + α[r + γ max Q(s',a') - Q(s,a)]
- Balance exploración-explotación mediante ε-greedy
- Convergencia hacia la función Q óptima
- Construcción incremental de la política óptima
"""

print("\n🤖 MÓDULO 5: Q-Learning Tabular - Implementación Detallada")
print("=" * 55)

class AgenteQLearning:
    """
    Implementación educativa de Q-Learning con instrumentación pedagógica completa.

    Esta clase está diseñada para revelar cada aspecto del proceso de aprendizaje,
    permitiendo a los estudiantes observar cómo emerge la inteligencia artificial
    a través de la experiencia acumulada.
    """

    def __init__(self, n_estados: int, n_acciones: int,
                 tasa_aprendizaje: float = 0.1, factor_descuento: float = 0.9,
                 epsilon_inicial: float = 1.0, decaimiento_epsilon: float = 0.995,
                 epsilon_minimo: float = 0.01):
        """
        Inicializa el agente Q-Learning con parámetros educativamente optimizados.

        Args:
            n_estados: Cardinalidad del espacio de estados |S|
            n_acciones: Cardinalidad del espacio de acciones |A|
            tasa_aprendizaje: α - Qué tan rápido aprende de nuevas experiencias
            factor_descuento: γ - Importancia de recompensas futuras vs inmediatas
            epsilon_inicial: Probabilidad inicial de exploración
            decaimiento_epsilon: Factor de reducción de exploración por episodio
            epsilon_minimo: Nivel mínimo de exploración para mantener adaptabilidad
        """
        self.n_estados = n_estados
        self.n_acciones = n_acciones
        self.alpha = tasa_aprendizaje
        self.gamma = factor_descuento
        self.epsilon = epsilon_inicial
        self.decaimiento_epsilon = decaimiento_epsilon
        self.epsilon_minimo = epsilon_minimo

        # Inicialización optimista de la tabla Q para fomentar exploración
        self.tabla_q = defaultdict(lambda: np.zeros(n_acciones))

        # Métricas pedagógicas para análisis del proceso de aprendizaje
        self.historial_recompensas = []
        self.historial_longitudes = []
        self.historial_epsilon = []
        self.historial_errores_td = []
        self.contador_actualizaciones = 0

        print(f"🧠 Agente Q-Learning inicializado:")
        print(f"   📊 Espacio de estados: {n_estados}")
        print(f"   🎮 Espacio de acciones: {n_acciones}")
        print(f"   📈 Tasa de aprendizaje (α): {tasa_aprendizaje}")
        print(f"   ⏰ Factor de descuento (γ): {factor_descuento}")
        print(f"   🔍 Exploración inicial (ε): {epsilon_inicial}")

    def seleccionar_accion(self, estado: int, modo_entrenamiento: bool = True) -> int:
        """
        Implementa la estrategia ε-greedy para balance exploración-explotación.

        La política ε-greedy constituye una solución elegante al dilema fundamental
        del aprendizaje por refuerzo: cómo balancear la exploración de nuevas
        posibilidades contra la explotación del conocimiento actual.

        Args:
            estado: Estado actual del agente
            modo_entrenamiento: Si aplica exploración (True) o usa política greedy (False)

        Returns:
            Acción seleccionada según la estrategia ε-greedy
        """
        if modo_entrenamiento and np.random.random() < self.epsilon:
            # EXPLORACIÓN: Selección aleatoria para descubrir nuevas estrategias
            accion = np.random.randint(0, self.n_acciones)
            tipo_seleccion = "exploración"
        else:
            # EXPLOTACIÓN: Selección greedy basada en conocimiento actual
            valores_q = self.tabla_q[estado]
            # Manejo de empates mediante selección aleatoria para robustez
            max_q = np.max(valores_q)
            mejores_acciones = np.where(valores_q == max_q)[0]
            accion = np.random.choice(mejores_acciones)
            tipo_seleccion = "explotación"

        # Registro para análisis pedagógico
        if hasattr(self, 'debug_mode') and self.debug_mode:
            print(f"   Estado {estado}: {tipo_seleccion} → acción {accion}")

        return accion

    def actualizar_q(self, estado: int, accion: int, recompensa: float,
                    siguiente_estado: int, terminado: bool) -> float:
        """
        Implementa la regla de actualización fundamental de Q-Learning.

        Esta función encapsula la esencia matemática del aprendizaje por refuerzo:
        Q(s,a) ← Q(s,a) + α[r + γ max_{a'} Q(s',a') - Q(s,a)]

        El término entre corchetes representa el "error de diferencia temporal" (TD error),
        que mide qué tan equivocada estaba nuestra estimación previa.

        Args:
            estado: Estado actual s
            accion: Acción ejecutada a
            recompensa: Recompensa observada r
            siguiente_estado: Estado resultante s'
            terminado: Si el episodio terminó

        Returns:
            Magnitud del error TD para análisis de convergencia
        """
        # Valor Q actual para la tupla (estado, acción)
        q_actual = self.tabla_q[estado][accion]

        # Cálculo del objetivo (target) según la ecuación de Q-Learning
        if terminado:
            # En estados terminales, no hay valor futuro
            q_objetivo = recompensa
        else:
            # En estados no terminales, incluimos el valor futuro óptimo descontado
            q_objetivo = recompensa + self.gamma * np.max(self.tabla_q[siguiente_estado])

        # Error de diferencia temporal: diferencia entre target y predicción actual
        error_td = q_objetivo - q_actual

        # Actualización incremental de la función Q
        self.tabla_q[estado][accion] += self.alpha * error_td

        # Registro de métricas para análisis pedagógico
        self.contador_actualizaciones += 1
        self.historial_errores_td.append(abs(error_td))

        return abs(error_td)

    def reducir_epsilon(self):
        """
        Implementa el decaimiento gradual de la exploración.

        A medida que el agente acumula experiencia, reduce gradualmente la exploración
        para converger hacia una política determinística óptima.
        """
        if self.epsilon > self.epsilon_minimo:
            self.epsilon *= self.decaimiento_epsilon

    def extraer_politica(self) -> np.ndarray:
        """
        Extrae la política determinística greedy de la función Q actual.

        Returns:
            Matriz de política π(a|s) donde cada fila suma 1
        """
        politica = np.zeros((self.n_estados, self.n_acciones))

        for estado in range(self.n_estados):
            valores_q = self.tabla_q[estado]
            mejor_accion = np.argmax(valores_q)
            politica[estado, mejor_accion] = 1.0

        return politica

    def extraer_funcion_valor(self) -> np.ndarray:
        """
        Calcula la función de valor de estado V(s) = max_a Q(s,a).

        Returns:
            Vector de función de valor para visualización
        """
        return np.array([np.max(self.tabla_q[estado]) for estado in range(self.n_estados)])

    def obtener_estadisticas_aprendizaje(self) -> Dict:
        """
        Proporciona métricas comprehensivas del proceso de aprendizaje.

        Returns:
            Diccionario con estadísticas detalladas para análisis pedagógico
        """
        return {
            'total_actualizaciones': self.contador_actualizaciones,
            'epsilon_actual': self.epsilon,
            'error_td_promedio': np.mean(self.historial_errores_td[-100:]) if self.historial_errores_td else 0,
            'convergencia_reciente': np.std(self.historial_errores_td[-50:]) if len(self.historial_errores_td) >= 50 else float('inf')
        }

# Demostración interactiva de los componentes del agente
print("\n🔍 DEMOSTRACIÓN: Componentes del Agente Q-Learning")

# Crear agente con parámetros educativos
agente_demo = AgenteQLearning(n_estados=env_educativo.n_estados,
                             n_acciones=env_educativo.n_acciones,
                             tasa_aprendizaje=0.1, factor_descuento=0.9)

# Activar modo debug para mostrar decisiones
agente_demo.debug_mode = True

print(f"\n📋 Simulación de decisiones iniciales (tabla Q vacía):")
for i in range(3):
    estado_ejemplo = np.random.randint(0, 5)  # Algunos estados de ejemplo
    accion = agente_demo.seleccionar_accion(estado_ejemplo)
    print(f"   Estado {estado_ejemplo}: Q = {agente_demo.tabla_q[estado_ejemplo]} → Acción {accion}")

# Desactivar modo debug
agente_demo.debug_mode = False

print(f"\n✅ Módulo 5 completado - Agente Q-Learning implementado")

# ============================================================================
# PAUSA PEDAGÓGICA 4
# ============================================================================

print("\n" + "="*60)
print("📚 PAUSA PEDAGÓGICA - ANATOMÍA DEL Q-LEARNING")
print("="*60)
print("""
CONCEPTOS FUNDAMENTALES IMPLEMENTADOS:

1. REGLA DE ACTUALIZACIÓN Q-LEARNING:
   - Q(s,a) ← Q(s,a) + α[r + γ max Q(s',a') - Q(s,a)]
   - α controla velocidad de aprendizaje (0 = no aprende, 1 = olvida todo lo anterior)
   - γ determina importancia del futuro (0 = miope, 1 = visionario)
   - Error TD mide qué tan equivocada estaba nuestra estimación

2. EXPLORACIÓN vs EXPLOTACIÓN:
   - ε-greedy balancea descubrimiento de nuevas estrategias vs uso del conocimiento actual
   - Decaimiento de ε: alta exploración inicial → explotación gradual
   - Sin exploración: convergencia prematura a políticas subóptimas

3. PROCESO DE APRENDIZAJE:
   - Tabla Q inicialmente vacía (o con valores optimistas)
   - Cada experiencia (s,a,r,s') actualiza una entrada específica
   - Convergencia gradual hacia Q*(s,a) - función Q óptima

EXPERIMENTO MENTAL:
¿Qué pasaría si α = 0? ¿Y si ε = 0 desde el inicio?
¿Cómo afecta γ a la estrategia del agente (miope vs planificador)?
""")
print("="*60)

# ============================================================================
# MÓDULO 6: ENTRENAMIENTO Y ANÁLISIS DE Q-LEARNING
# ============================================================================

"""
## MÓDULO 6: ENTRENAMIENTO SUPERVISADO DE Q-LEARNING

**OBJETIVO PEDAGÓGICO:**
Observar el proceso completo de aprendizaje, desde la exploración aleatoria inicial
hasta la emergencia de comportamiento inteligente y la convergencia a políticas óptimas.

**CONCEPTOS CLAVE:**
- Curvas de aprendizaje y métricas de convergencia
- Evolución de la exploración a lo largo del tiempo
- Análisis de la política emergente
- Evaluación sistemática del rendimiento
"""

print("\n🎓 MÓDULO 6: Entrenamiento Supervisado de Q-Learning")
print("=" * 50)

def entrenar_agente_qlearning(env, agente, n_episodios: int = 300,
                             mostrar_progreso: bool = True,
                             intervalo_reporte: int = 50) -> Dict:
    """
    Función educativa para entrenar un agente Q-Learning con análisis pedagógico completo.

    Esta función no solo entrena al agente, sino que proporciona insights detallados
    sobre cada fase del proceso de aprendizaje, desde la exploración inicial hasta
    la convergencia hacia comportamiento óptimo.

    Args:
        env: Entorno de aprendizaje por refuerzo
        agente: Agente Q-Learning a entrenar
        n_episodios: Número total de episodios de entrenamiento
        mostrar_progreso: Mostrar reportes periódicos del progreso
        intervalo_reporte: Frecuencia de reportes (cada N episodios)

    Returns:
        Diccionario comprehensivo con métricas de entrenamiento
    """
    print(f"🚀 INICIANDO PROCESO DE ENTRENAMIENTO Q-LEARNING")
    print(f"📊 Configuración: {n_episodios} episodios, reportes cada {intervalo_reporte}")
    print("-" * 60)

    # Contenedores para métricas pedagógicas
    metricas_entrenamiento = {
        'recompensas_episodio': [],
        'longitudes_episodio': [],
        'valores_epsilon': [],
        'errores_td_promedio': [],
        'estados_visitados': [],
        'tiempo_convergencia': None
    }

    # Variables para detección de convergencia
    ventana_recompensas = deque(maxlen=100)
    mejor_promedio = -np.inf
    episodios_estables = 0
    umbral_convergencia = 0.8  # Recompensa promedio para considerar convergencia

    print(f"🎯 Iniciando entrenamiento...")
    tiempo_inicio = time.time()

    for episodio in range(n_episodios):
        # Reiniciar entorno para nuevo episodio
        estado = env.reset()
        recompensa_episodio = 0
        longitud_episodio = 0
        errores_td_episodio = []
        estados_visitados_episodio = set()

        # Ejecutar episodio completo
        while True:
            # Seleccionar acción según política ε-greedy
            accion = agente.seleccionar_accion(estado, modo_entrenamiento=True)

            # Ejecutar acción en el entorno
            siguiente_estado, recompensa, terminado, info = env.step(accion)

            # Actualizar función Q y registrar error TD
            error_td = agente.actualizar_q(estado, accion, recompensa,
                                         siguiente_estado, terminado)
            errores_td_episodio.append(error_td)

            # Registrar métricas del episodio
            recompensa_episodio += recompensa
            longitud_episodio += 1
            estados_visitados_episodio.add(estado)

            # Preparar para siguiente iteración
            estado = siguiente_estado

            # Verificar terminación
            if terminado or longitud_episodio > 100:  # Evitar episodios infinitos
                break

        # Actualizar exploración
        agente.reducir_epsilon()

        # Registrar métricas del episodio
        metricas_entrenamiento['recompensas_episodio'].append(recompensa_episodio)
        metricas_entrenamiento['longitudes_episodio'].append(longitud_episodio)
        metricas_entrenamiento['valores_epsilon'].append(agente.epsilon)
        metricas_entrenamiento['errores_td_promedio'].append(np.mean(errores_td_episodio))
        metricas_entrenamiento['estados_visitados'].append(len(estados_visitados_episodio))

        # Análisis de convergencia
        ventana_recompensas.append(recompensa_episodio)
        promedio_reciente = np.mean(ventana_recompensas) if ventana_recompensas else 0

        # Detección de convergencia
        if promedio_reciente > mejor_promedio and len(ventana_recompensas) == 100:
            mejor_promedio = promedio_reciente
            if promedio_reciente >= umbral_convergencia:
                episodios_estables += 1
                if episodios_estables >= 20 and metricas_entrenamiento['tiempo_convergencia'] is None:
                    metricas_entrenamiento['tiempo_convergencia'] = episodio
                    if mostrar_progreso:
                        print(f"🎯 ¡CONVERGENCIA DETECTADA en episodio {episodio}!")

        # Reportes periódicos con análisis pedagógico
        if mostrar_progreso and (episodio + 1) % intervalo_reporte == 0:
            stats = agente.obtener_estadisticas_aprendizaje()
            exploracion_actual = f"{agente.epsilon:.3f}"
            cobertura_estados = len(set(range(env.n_estados)) &
                                   set().union(*[{s} for s in metricas_entrenamiento['estados_visitados'][-intervalo_reporte:]]))

            print(f"📈 Episodio {episodio + 1:3d} | "
                  f"R: {recompensa_episodio:5.1f} | "
                  f"L: {longitud_episodio:3d} | "
                  f"ε: {exploracion_actual} | "
                  f"Prom(100): {promedio_reciente:5.2f} | "
                  f"Estados: {cobertura_estados:2d}/{env.n_estados}")

    tiempo_total = time.time() - tiempo_inicio

    print(f"\n✅ ENTRENAMIENTO COMPLETADO")
    print(f"   ⏱️  Tiempo total: {tiempo_total:.1f}s")
    print(f"   🔄 Actualizaciones Q: {agente.contador_actualizaciones:,}")
    print(f"   🎯 Exploración final: {agente.epsilon:.4f}")
    print(f"   📊 Rendimiento final (100 ep.): {np.mean(ventana_recompensas):.3f}")

    return metricas_entrenamiento

# Ejecutar entrenamiento con nuestro agente y entorno
print(f"\n🎮 Iniciando entrenamiento en GridWorld {env_educativo.altura}×{env_educativo.ancho}")
agente_qlearning = AgenteQLearning(n_estados=env_educativo.n_estados,
                                  n_acciones=env_educativo.n_acciones)

resultados_entrenamiento = entrenar_agente_qlearning(env_educativo, agente_qlearning,
                                                   n_episodios=300, mostrar_progreso=True)

print("\n✅ Módulo 6 completado - Entrenamiento Q-Learning finalizado")

# ============================================================================
# MÓDULO 6B: ANÁLISIS Y VISUALIZACIÓN DE RESULTADOS
# ============================================================================

"""
## MÓDULO 6B: ANÁLISIS PROFUNDO DE LOS RESULTADOS DE Q-LEARNING

**OBJETIVO PEDAGÓGICO:**
Desarrollar habilidades de análisis de datos de aprendizaje automático y
comprensión profunda de las métricas de convergencia y rendimiento.
"""

print("\n📊 MÓDULO 6B: Análisis de Resultados Q-Learning")
print("=" * 50)

def visualizar_analisis_qlearning(metricas: Dict, agente: AgenteQLearning, env):
    """
    Genera visualizaciones educativas comprehensivas del proceso de aprendizaje.

    Args:
        metricas: Diccionario con métricas de entrenamiento
        agente: Agente entrenado para extraer política
        env: Entorno para visualización de política
    """

    # Configurar subplots para análisis múltiple
    fig, axes = plt.subplots(2, 2, figsize=(15, 10))

    episodios = range(1, len(metricas['recompensas_episodio']) + 1)

    # 1. Evolución de recompensas con media móvil
    axes[0,0].plot(episodios, metricas['recompensas_episodio'], alpha=0.3,
                  color='blue', label='Recompensa por episodio')

    # Calcular y mostrar media móvil
    ventana = 20
    if len(metricas['recompensas_episodio']) >= ventana:
        media_movil = np.convolve(metricas['recompensas_episodio'],
                                np.ones(ventana)/ventana, mode='valid')
        axes[0,0].plot(episodios[ventana-1:], media_movil, color='red',
                      linewidth=2, label=f'Media móvil ({ventana} ep.)')

    axes[0,0].set_title('Evolución del Rendimiento', fontweight='bold')
    axes[0,0].set_xlabel('Episodio')
    axes[0,0].set_ylabel('Recompensa Acumulada')
    axes[0,0].legend()
    axes[0,0].grid(True, alpha=0.3)

    # 2. Eficiencia del agente (longitud de episodios)
    axes[0,1].plot(episodios, metricas['longitudes_episodio'], color='green', alpha=0.7)
    axes[0,1].set_title('Eficiencia del Agente', fontweight='bold')
    axes[0,1].set_xlabel('Episodio')
    axes[0,1].set_ylabel('Pasos hasta Terminación')
    axes[0,1].grid(True, alpha=0.3)

    # 3. Decaimiento de exploración
    axes[1,0].plot(episodios, metricas['valores_epsilon'], color='orange', linewidth=2)
    axes[1,0].set_title('Evolución de la Exploración', fontweight='bold')
    axes[1,0].set_xlabel('Episodio')
    axes[1,0].set_ylabel('Epsilon (ε)')
    axes[1,0].grid(True, alpha=0.3)

    # 4. Convergencia del algoritmo (errores TD)
    axes[1,1].plot(episodios, metricas['errores_td_promedio'], color='purple', alpha=0.7)
    axes[1,1].set_title('Convergencia del Algoritmo', fontweight='bold')
    axes[1,1].set_xlabel('Episodio')
    axes[1,1].set_ylabel('Error TD Promedio')
    axes[1,1].grid(True, alpha=0.3)

    plt.tight_layout(rect=[0, 0, 1, 0.95])
    plt.suptitle('Análisis Comprehensivo: Entrenamiento Q-Learning',
                fontsize=16, fontweight='bold', y=0.98)
    plt.show()

# Generar análisis visual
visualizar_analisis_qlearning(resultados_entrenamiento, agente_qlearning, env_educativo)

# Extraer y mostrar la política aprendida
print(f"\n🧠 ANÁLISIS DE LA POLÍTICA APRENDIDA:")
politica_aprendida = agente_qlearning.extraer_politica()
funcion_valor = agente_qlearning.extraer_funcion_valor()

print(f"   📊 Estados explorados: {len([s for s in range(env_educativo.n_estados) if np.any(politica_aprendida[s])])}")
print(f"   🎯 Valor máximo alcanzado: {np.max(funcion_valor):.3f}")
print(f"   📈 Rango de valores: [{np.min(funcion_valor):.3f}, {np.max(funcion_valor):.3f}]")

# Visualizar política en el entorno
env_educativo.reset()
env_educativo.visualizar(politica=politica_aprendida, funcion_valor=funcion_valor,
                        titulo="Política Óptima Aprendida - Q-Learning Tabular")

print("\n✅ Módulo 6B completado - Análisis de resultados Q-Learning")

# ============================================================================
# PAUSA PEDAGÓGICA 5
# ============================================================================

print("\n" + "="*60)
print("📚 PAUSA PEDAGÓGICA - INTERPRETACIÓN DE RESULTADOS Q-LEARNING")
print("="*60)
print("""
ANÁLISIS DE LAS VISUALIZACIONES:

1. CURVA DE APRENDIZAJE (Recompensas):
   - Tendencia ascendente indica aprendizaje exitoso
   - Variabilidad inicial refleja exploración
   - Estabilización sugiere convergencia a política óptima

2. EFICIENCIA (Longitud de episodios):
   - Disminución indica que el agente encuentra rutas más directas
   - Estabilización en valores bajos = política eficiente
   - Picos ocasionales = exploración residual (ε > 0)

3. EXPLORACIÓN (Decaimiento de ε):
   - Reducción exponencial balanceada
   - Nunca llega a cero = mantiene adaptabilidad
   - Tasa de decaimiento afecta velocidad de convergencia

4. CONVERGENCIA (Errores TD):
   - Tendencia descendente = función Q se estabiliza
   - Fluctuaciones = variabilidad natural del aprendizaje
   - Valores cercanos a cero = política cerca del óptimo

PREGUNTAS DE REFLEXIÓN:
- ¿Qué indica si la recompensa promedio se estanca?
- ¿Por qué mantener ε > 0 incluso después de convergencia?
- ¿Cómo afectaría un α muy alto o muy bajo?
""")
print("="*60)

# ============================================================================
# MÓDULO 7: DEEP Q-NETWORKS - TEORÍA E IMPLEMENTACIÓN
# ============================================================================

"""
## MÓDULO 7: DEEP Q-NETWORKS (DQN) - APROXIMACIÓN FUNCIONAL

**OBJETIVO PEDAGÓGICO:**
Comprender la transición de métodos tabulares a aproximación funcional,
implementando las innovaciones clave que hacen posible el Deep Q-Learning.

**CONCEPTOS CLAVE:**
- Aproximación funcional Q_θ(s,a) mediante redes neuronales
- Experience Replay para romper correlaciones temporales
- Target Network para estabilización del entrenamiento
- Optimización de redes neuronales para RL
"""

print("\n🧠 MÓDULO 7: Deep Q-Networks - Aproximación Funcional")
print("=" * 55)

# Detectar y configurar entorno CartPole
def crear_entorno_cartpole():
    """
    Crea entorno CartPole con compatibilidad multi-versión.

    Returns:
        Tupla (entorno, tipo_gym, dimensiones)
    """
    try:
        import gymnasium as gym
        env = gym.make('CartPole-v1', render_mode=None)
        tipo = 'gymnasium'
        print("✅ Utilizando Gymnasium para CartPole")
    except ImportError:
        import gym
        env = gym.make('CartPole-v1')
        tipo = 'gym'
        print("✅ Utilizando OpenAI Gym para CartPole")

    # Obtener dimensiones del problema
    if tipo == 'gymnasium':
        dim_estado = env.observation_space.shape[0]
        dim_accion = env.action_space.n
    else:
        dim_estado = env.observation_space.shape[0]
        dim_accion = env.action_space.n

    print(f"   🎯 Estados: {dim_estado} dimensiones continuas")
    print(f"   🎮 Acciones: {dim_accion} (izquierda/derecha)")

    return env, tipo, dim_estado, dim_accion

# Crear entorno CartPole
env_cartpole, tipo_gym, dim_estados, dim_acciones = crear_entorno_cartpole()

class RedQProfunda(nn.Module):
    """
    Arquitectura de red neuronal optimizada para aproximación de función Q.

    Esta implementación utiliza principios de diseño probados en literatura:
    - Capas densas con activaciones ReLU para capacidad expresiva
    - Dimensiones decrecientes para compresión jerárquica
    - Dropout para regularización y prevención de sobreajuste
    """

    def __init__(self, dim_entrada: int, dim_salida: int,
                 capas_ocultas: List[int] = [256, 128, 64]):
        """
        Inicializa la arquitectura de la red Q.

        Args:
            dim_entrada: Dimensionalidad del espacio de estados
            dim_salida: Número de acciones disponibles
            capas_ocultas: Lista con dimensiones de capas ocultas
        """
        super(RedQProfunda, self).__init__()

        # Construcción dinámica de la arquitectura
        capas = []
        dim_previa = dim_entrada

        for dim_oculta in capas_ocultas:
            capas.extend([
                nn.Linear(dim_previa, dim_oculta),
                nn.ReLU(),
                nn.Dropout(0.1)  # Regularización ligera
            ])
            dim_previa = dim_oculta

        # Capa de salida sin activación (valores Q pueden ser negativos)
        capas.append(nn.Linear(dim_previa, dim_salida))

        self.red = nn.Sequential(*capas)

        # Inicialización Xavier para convergencia estable
        self._inicializar_pesos()

        # Calcular parámetros totales para reporte
        total_params = sum(p.numel() for p in self.parameters())

        print(f"🏗️  Red DQN construida:")
        print(f"   📐 Arquitectura: {[dim_entrada] + capas_ocultas + [dim_salida]}")
        print(f"   📊 Parámetros totales: {total_params:,}")
        print(f"   🎯 Entrada: {dim_entrada}D → Salida: {dim_salida} valores Q")

    def _inicializar_pesos(self):
        """Inicialización Xavier/Glorot para estabilidad de entrenamiento."""
        for modulo in self.modules():
            if isinstance(modulo, nn.Linear):
                nn.init.xavier_uniform_(modulo.weight)
                nn.init.constant_(modulo.bias, 0.0)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        """
        Propagación hacia adelante para calcular valores Q.

        Args:
            x: Tensor de estados [batch_size, dim_entrada]

        Returns:
            Valores Q para todas las acciones [batch_size, dim_salida]
        """
        return self.red(x)

class BufferExperienceReplay:
    """
    Buffer circular para Experience Replay con muestreo eficiente.

    Experience Replay constituye una innovación fundamental en DQN que rompe
    la correlación temporal entre experiencias consecutivas, permitiendo
    un aprendizaje más estable y eficiente de la función Q.
    """

    def __init__(self, capacidad: int = 10000):
        """
        Inicializa buffer circular de experiencias.

        Args:
            capacidad: Número máximo de transiciones a almacenar
        """
        self.buffer = deque(maxlen=capacidad)
        self.Transicion = namedtuple('Transicion',
                                   ['estado', 'accion', 'recompensa', 'siguiente_estado', 'terminado'])

        print(f"💾 Buffer Experience Replay creado:")
        print(f"   📊 Capacidad: {capacidad:,} transiciones")
        print(f"   🔄 Tipo: Buffer circular (FIFO cuando lleno)")

    def almacenar(self, estado: np.ndarray, accion: int, recompensa: float,
                 siguiente_estado: np.ndarray, terminado: bool):
        """
        Almacena nueva transición en el buffer.

        Args:
            estado: Estado actual
            accion: Acción ejecutada
            recompensa: Recompensa observada
            siguiente_estado: Estado resultante
            terminado: Flag de terminación del episodio
        """
        transicion = self.Transicion(estado, accion, recompensa, siguiente_estado, terminado)
        self.buffer.append(transicion)

    def muestrear(self, tamaño_lote: int) -> List:
        """
        Muestrea aleatoriamente un lote de transiciones.

        Args:
            tamaño_lote: Número de transiciones a muestrear

        Returns:
            Lista de transiciones muestreadas aleatoriamente
        """
        return random.sample(self.buffer, min(tamaño_lote, len(self.buffer)))

    def __len__(self) -> int:
        """Retorna número actual de transiciones almacenadas."""
        return len(self.buffer)

# Demostrar componentes DQN
print(f"\n🔬 DEMOSTRACIÓN: Componentes de Deep Q-Network")

# Crear red neuronal de ejemplo
red_demo = RedQProfunda(dim_entrada=dim_estados, dim_salida=dim_acciones)

# Crear buffer de experience replay
buffer_demo = BufferExperienceReplay(capacidad=5000)

# Simular almacenamiento de experiencias
print(f"\n📝 Simulando almacenamiento de experiencias:")
for i in range(10):
    estado_falso = np.random.random(dim_estados).astype(np.float32)
    accion_falsa = np.random.randint(0, dim_acciones)
    recompensa_falsa = np.random.random()
    siguiente_estado_falso = np.random.random(dim_estados).astype(np.float32)
    terminado_falso = np.random.random() < 0.1

    buffer_demo.almacenar(estado_falso, accion_falsa, recompensa_falsa,
                         siguiente_estado_falso, terminado_falso)

print(f"   📊 Experiencias almacenadas: {len(buffer_demo)}")

# Demostrar muestreo
lote_ejemplo = buffer_demo.muestrear(3)
print(f"   🎲 Lote muestreado: {len(lote_ejemplo)} transiciones")

# Demostrar propagación hacia adelante
with torch.no_grad():
    estado_tensor = torch.FloatTensor(estado_falso).unsqueeze(0)
    valores_q = red_demo(estado_tensor)
    print(f"   🧠 Salida de la red: {valores_q.shape} → Q-values: {valores_q.squeeze().numpy()}")

print("\n✅ Módulo 7 completado - Componentes DQN implementados")

# ============================================================================
# PAUSA PEDAGÓGICA 6
# ============================================================================

print("\n" + "="*60)
print("📚 PAUSA PEDAGÓGICA - INNOVACIONES EN DEEP Q-NETWORKS")
print("="*60)
print("""
TRANSICIÓN: TABULAR → APROXIMACIÓN FUNCIONAL

1. LIMITACIONES DEL Q-LEARNING TABULAR:
   - Escalabilidad: |S| × |A| crece exponencialmente
   - Generalización: No aprovecha similitudes entre estados
   - Memoria: Almacenamiento prohibitivo para espacios grandes

2. SOLUCIÓN: APROXIMACIÓN FUNCIONAL
   - Q_θ(s,a): Red neuronal parametrizada por θ
   - Generalización automática a estados no visitados
   - Capacidad expresiva para funciones complejas

3. DESAFÍOS Y SOLUCIONES DQN:

   PROBLEMA: Correlación temporal de experiencias
   SOLUCIÓN: Experience Replay → muestreo aleatorio rompe correlaciones

   PROBLEMA: Inestabilidad en targets móviles
   SOLUCIÓN: Target Network → targets estables por períodos fijos

   PROBLEMA: Distribución de datos no-estacionaria
   SOLUCIÓN: Técnicas de regularización y optimización cuidadosa

4. ARQUITECTURA DE RED:
   - Entrada: Vector de estado (ej: 4D para CartPole)
   - Capas ocultas: Transformaciones no lineales
   - Salida: Vector de Q-values (uno por acción)

INSIGHT CLAVE: DQN mantiene la elegancia matemática de Q-Learning
pero escala a problemas complejos mediante aproximación funcional.
""")
print("="*60)

print("\n🎓 ¡Preparado para el módulo final!")
print("En el siguiente bloque entrenaremos el agente DQN completo...")

# ============================================================================
# MÓDULO 8: AGENTE DQN COMPLETO Y ANÁLISIS COMPARATIVO
# ============================================================================

"""
## MÓDULO 8: IMPLEMENTACIÓN COMPLETA DE DEEP Q-NETWORKS

**OBJETIVO PEDAGÓGICO:**
Integrar todos los componentes en un agente DQN funcional, observar su
entrenamiento en un problema de estados continuos, y realizar un análisis
comparativo comprehensivo con Q-Learning tabular.

**CONCEPTOS CLAVE:**
- Integración de todos los componentes DQN
- Entrenamiento en espacios de estados continuos
- Análisis comparativo: tabular vs aproximación funcional
- Escalabilidad y limitaciones de cada enfoque
"""

print("\n🚀 MÓDULO 8: Agente DQN Completo - Integración Final")
print("=" * 55)

class AgenteDQN:
    """
    Implementación completa de Deep Q-Network con todas las mejoras algorítmicas.

    Esta clase integra todas las innovaciones de DQN en una implementación
    pedagógicamente clara que permite comprender cada componente y su función
    en el algoritmo completo.
    """

    def __init__(self, dim_estado: int, dim_accion: int,
                 tasa_aprendizaje: float = 1e-3, factor_descuento: float = 0.99,
                 epsilon_inicial: float = 1.0, decaimiento_epsilon: float = 0.995,
                 epsilon_minimo: float = 0.01, tamaño_memoria: int = 10000,
                 tamaño_lote: int = 32, frecuencia_actualizacion_target: int = 100):
        """
        Inicializa el agente DQN con todos los hiperparámetros pedagógicamente explicados.

        Args:
            dim_estado: Dimensionalidad del espacio de estados
            dim_accion: Número de acciones disponibles
            tasa_aprendizaje: Learning rate para el optimizador Adam
            factor_descuento: γ - Factor de descuento temporal
            epsilon_inicial: ε inicial para exploración
            decaimiento_epsilon: Factor de decaimiento de ε por episodio
            epsilon_minimo: ε mínimo para mantener exploración residual
            tamaño_memoria: Capacidad del buffer de experience replay
            tamaño_lote: Tamaño de lote para entrenamiento de la red
            frecuencia_actualizacion_target: Cada cuántos pasos actualizar target network
        """
        self.dim_estado = dim_estado
        self.dim_accion = dim_accion
        self.epsilon = epsilon_inicial
        self.decaimiento_epsilon = decaimiento_epsilon
        self.epsilon_minimo = epsilon_minimo
        self.gamma = factor_descuento
        self.tamaño_lote = tamaño_lote
        self.frecuencia_target = frecuencia_actualizacion_target

        # Detectar dispositivo computacional óptimo
        self.dispositivo = torch.device("cuda" if torch.cuda.is_available() else "cpu")

        # Inicializar redes neuronales gemelas
        self.red_q = RedQProfunda(dim_estado, dim_accion).to(self.dispositivo)
        self.red_target = RedQProfunda(dim_estado, dim_accion).to(self.dispositivo)

        # Sincronizar red target inicialmente
        self.actualizar_red_target()

        # Configurar optimizador con regularización L2
        self.optimizador = optim.Adam(self.red_q.parameters(),
                                    lr=tasa_aprendizaje, weight_decay=1e-4)

        # Función de pérdida
        self.criterio = nn.MSELoss()

        # Experience Replay
        self.memoria = BufferExperienceReplay(tamaño_memoria)

        # Métricas de entrenamiento para análisis pedagógico
        self.paso_entrenamiento = 0
        self.historial_perdidas = []
        self.historial_q_values = []
        self.historial_epsilon = []

        print(f"🤖 Agente DQN inicializado:")
        print(f"   🖥️  Dispositivo: {self.dispositivo}")
        print(f"   🧠 Arquitectura: Red principal + Red target")
        print(f"   📊 Parámetros: LR={tasa_aprendizaje}, γ={factor_descuento}")
        print(f"   🎯 Memoria: {tamaño_memoria:,} experiencias")
        print(f"   🔄 Actualización target: cada {frecuencia_actualizacion_target} pasos")

    def actuar(self, estado: np.ndarray, modo_entrenamiento: bool = True) -> int:
        """
        Selecciona acción usando política ε-greedy con red neuronal.

        Args:
            estado: Estado actual del entorno
            modo_entrenamiento: Si aplicar exploración (True) o política greedy (False)

        Returns:
            Acción seleccionada
        """
        if modo_entrenamiento and np.random.random() < self.epsilon:
            # Exploración: acción aleatoria
            return np.random.randint(0, self.dim_accion)

        # Explotación: usar red neuronal para seleccionar mejor acción
        estado_tensor = torch.FloatTensor(estado).unsqueeze(0).to(self.dispositivo)

        with torch.no_grad():
            q_values = self.red_q(estado_tensor)
            # Registrar Q-values promedio para análisis
            self.historial_q_values.append(q_values.mean().item())

        return q_values.argmax().item()

    def recordar(self, estado: np.ndarray, accion: int, recompensa: float,
                siguiente_estado: np.ndarray, terminado: bool):
        """Almacena experiencia en el buffer de replay."""
        self.memoria.almacenar(estado, accion, recompensa, siguiente_estado, terminado)

    def aprender(self) -> float:
        """
        Realiza una actualización de los parámetros de la red Q usando experience replay.

        Returns:
            Valor de la pérdida para monitoreo de convergencia
        """
        if len(self.memoria) < self.tamaño_lote:
            return 0.0

        # Muestrear lote de experiencias
        lote = self.memoria.muestrear(self.tamaño_lote)

        # Convertir lote a tensores optimizados
        estados = torch.FloatTensor([t.estado for t in lote]).to(self.dispositivo)
        acciones = torch.LongTensor([t.accion for t in lote]).to(self.dispositivo)
        recompensas = torch.FloatTensor([t.recompensa for t in lote]).to(self.dispositivo)
        siguientes_estados = torch.FloatTensor([t.siguiente_estado for t in lote]).to(self.dispositivo)
        terminados = torch.BoolTensor([t.terminado for t in lote]).to(self.dispositivo)

        # Calcular Q-values actuales para las acciones tomadas
        q_values_actuales = self.red_q(estados).gather(1, acciones.unsqueeze(1)).squeeze(1)

        # Calcular Q-values objetivo usando red target (Double DQN)
        with torch.no_grad():
            q_values_siguiente = self.red_target(siguientes_estados).max(1)[0]
            q_targets = recompensas + (self.gamma * q_values_siguiente * ~terminados)

        # Calcular pérdida y realizar backpropagation
        perdida = self.criterio(q_values_actuales, q_targets)

        self.optimizador.zero_grad()
        perdida.backward()

        # Gradient clipping para estabilidad numérica
        torch.nn.utils.clip_grad_norm_(self.red_q.parameters(), max_norm=1.0)

        self.optimizador.step()

        # Actualizar red target periódicamente
        self.paso_entrenamiento += 1
        if self.paso_entrenamiento % self.frecuencia_target == 0:
            self.actualizar_red_target()

        # Decaimiento de exploración
        if self.epsilon > self.epsilon_minimo:
            self.epsilon *= self.decaimiento_epsilon

        # Registrar métricas
        valor_perdida = perdida.item()
        self.historial_perdidas.append(valor_perdida)
        self.historial_epsilon.append(self.epsilon)

        return valor_perdida

    def actualizar_red_target(self):
        """Copia parámetros de la red principal a la red target."""
        self.red_target.load_state_dict(self.red_q.state_dict())

    def obtener_estadisticas(self) -> Dict:
        """
        Proporciona métricas comprehensivas del entrenamiento DQN.

        Returns:
            Diccionario con estadísticas para análisis pedagógico
        """
        return {
            'pasos_entrenamiento': self.paso_entrenamiento,
            'epsilon_actual': self.epsilon,
            'experiencias_memoria': len(self.memoria),
            'perdida_promedio': np.mean(self.historial_perdidas[-100:]) if self.historial_perdidas else 0,
            'q_value_promedio': np.mean(self.historial_q_values[-100:]) if self.historial_q_values else 0
        }

def entrenar_agente_dqn(env, agente_dqn, n_episodios: int = 500,
                       pasos_maximos: int = 500, mostrar_progreso: bool = True) -> Dict:
    """
    Función educativa para entrenar agente DQN con análisis pedagógico completo.

    Args:
        env: Entorno de entrenamiento (CartPole)
        agente_dqn: Agente DQN a entrenar
        n_episodios: Número de episodios de entrenamiento
        pasos_maximos: Máximo de pasos por episodio
        mostrar_progreso: Mostrar reportes periódicos

    Returns:
        Diccionario con métricas completas del entrenamiento
    """
    print(f"\n🎯 INICIANDO ENTRENAMIENTO DEEP Q-NETWORK")
    print(f"🎮 Entorno: CartPole-v1 (estados continuos)")
    print(f"📊 Configuración: {n_episodios} episodios, máx {pasos_maximos} pasos/episodio")
    print("-" * 65)

    # Contenedores para métricas
    metricas_dqn = {
        'recompensas_episodio': [],
        'longitudes_episodio': [],
        'perdidas_entrenamiento': [],
        'valores_epsilon': [],
        'q_values_promedio': []
    }

    # Variables para análisis de convergencia
    ventana_rendimiento = deque(maxlen=100)
    mejor_promedio = -np.inf
    tiempo_inicio = time.time()

    for episodio in range(n_episodios):
        # Reiniciar entorno
        if tipo_gym == 'gymnasium':
            estado, _ = env.reset()
        else:
            estado = env.reset()

        estado = np.array(estado, dtype=np.float32)
        recompensa_episodio = 0
        perdida_episodio = 0
        pasos = 0

        # Ejecutar episodio completo
        for paso in range(pasos_maximos):
            # Seleccionar y ejecutar acción
            accion = agente_dqn.actuar(estado, modo_entrenamiento=True)

            if tipo_gym == 'gymnasium':
                siguiente_estado, recompensa, terminado, truncado, _ = env.step(accion)
                terminado = terminado or truncado
            else:
                siguiente_estado, recompensa, terminado, _ = env.step(accion)

            siguiente_estado = np.array(siguiente_estado, dtype=np.float32)

            # Almacenar experiencia y aprender
            agente_dqn.recordar(estado, accion, recompensa, siguiente_estado, terminado)
            perdida = agente_dqn.aprender()

            # Actualizar métricas
            recompensa_episodio += recompensa
            perdida_episodio += perdida
            pasos += 1
            estado = siguiente_estado

            if terminado:
                break

        # Registrar métricas del episodio
        metricas_dqn['recompensas_episodio'].append(recompensa_episodio)
        metricas_dqn['longitudes_episodio'].append(pasos)
        metricas_dqn['valores_epsilon'].append(agente_dqn.epsilon)

        if perdida_episodio > 0:
            metricas_dqn['perdidas_entrenamiento'].append(perdida_episodio / pasos)

        # Análisis de rendimiento
        ventana_rendimiento.append(recompensa_episodio)
        promedio_reciente = np.mean(ventana_rendimiento)

        if promedio_reciente > mejor_promedio and len(ventana_rendimiento) == 100:
            mejor_promedio = promedio_reciente

        # Reportes periódicos con métricas educativas
        if mostrar_progreso and (episodio + 1) % 100 == 0:
            stats = agente_dqn.obtener_estadisticas()
            tiempo_transcurrido = time.time() - tiempo_inicio

            print(f"📈 Ep. {episodio + 1:3d} | "
                  f"R: {recompensa_episodio:6.1f} | "
                  f"Prom(100): {promedio_reciente:6.1f} | "
                  f"ε: {agente_dqn.epsilon:.3f} | "
                  f"Memoria: {len(agente_dqn.memoria):5,} | "
                  f"Tiempo: {tiempo_transcurrido:.0f}s")

    tiempo_total = time.time() - tiempo_inicio

    print(f"\n✅ ENTRENAMIENTO DQN COMPLETADO")
    print(f"   ⏱️  Tiempo total: {tiempo_total:.1f}s")
    print(f"   🔄 Pasos de entrenamiento: {agente_dqn.paso_entrenamiento:,}")
    print(f"   🧠 Experiencias acumuladas: {len(agente_dqn.memoria):,}")
    print(f"   🎯 Mejor promedio (100 ep.): {mejor_promedio:.1f}")
    print(f"   🔍 Exploración final: {agente_dqn.epsilon:.4f}")

    return metricas_dqn

# Crear y entrenar agente DQN
print(f"\n🎮 Creando agente DQN para CartPole...")
agente_dqn = AgenteDQN(dim_estado=dim_estados, dim_accion=dim_acciones,
                      tasa_aprendizaje=0.001, factor_descuento=0.99)

# Entrenamiento
resultados_dqn = entrenar_agente_dqn(env_cartpole, agente_dqn, n_episodios=500)

print("\n✅ Módulo 8 completado - Agente DQN entrenado exitosamente")

# ============================================================================
# MÓDULO 8B: ANÁLISIS COMPARATIVO COMPREHENSIVO
# ============================================================================

"""
## MÓDULO 8B: ANÁLISIS COMPARATIVO - TABULAR vs APROXIMACIÓN FUNCIONAL

**OBJETIVO PEDAGÓGICO:**
Desarrollar comprensión profunda de las fortalezas y limitaciones de cada
enfoque, identificando cuándo usar cada método según las características
del problema.
"""

print("\n📊 MÓDULO 8B: Análisis Comparativo Q-Learning vs DQN")
print("=" * 55)

def visualizar_comparacion_algoritmos(resultados_qlearning: Dict, resultados_dqn: Dict):
    """
    Genera visualizaciones comparativas entre Q-Learning tabular y DQN.

    Args:
        resultados_qlearning: Métricas del entrenamiento Q-Learning
        resultados_dqn: Métricas del entrenamiento DQN
    """

    fig, axes = plt.subplots(2, 3, figsize=(18, 10))

    # 1. Comparación de curvas de aprendizaje
    episodios_q = range(1, len(resultados_qlearning['recompensas_episodio']) + 1)
    episodios_dqn = range(1, len(resultados_dqn['recompensas_episodio']) + 1)

    axes[0,0].plot(episodios_q, resultados_qlearning['recompensas_episodio'],
                  alpha=0.3, color='blue', label='Q-Learning (GridWorld)')
    axes[0,0].plot(episodios_dqn, resultados_dqn['recompensas_episodio'],
                  alpha=0.3, color='red', label='DQN (CartPole)')

    # Medias móviles para claridad
    ventana = 20
    if len(resultados_qlearning['recompensas_episodio']) >= ventana:
        media_q = np.convolve(resultados_qlearning['recompensas_episodio'],
                             np.ones(ventana)/ventana, mode='valid')
        axes[0,0].plot(episodios_q[ventana-1:], media_q, color='darkblue', linewidth=2)

    if len(resultados_dqn['recompensas_episodio']) >= ventana:
        media_dqn = np.convolve(resultados_dqn['recompensas_episodio'],
                               np.ones(ventana)/ventana, mode='valid')
        axes[0,0].plot(episodios_dqn[ventana-1:], media_dqn, color='darkred', linewidth=2)

    axes[0,0].set_title('Curvas de Aprendizaje Comparativas', fontweight='bold')
    axes[0,0].set_xlabel('Episodio')
    axes[0,0].set_ylabel('Recompensa')
    axes[0,0].legend()
    axes[0,0].grid(True, alpha=0.3)

    # 2. Eficiencia (longitud de episodios)
    axes[0,1].plot(episodios_q, resultados_qlearning['longitudes_episodio'],
                  color='blue', alpha=0.6, label='Q-Learning')
    axes[0,1].plot(episodios_dqn, resultados_dqn['longitudes_episodio'],
                  color='red', alpha=0.6, label='DQN')
    axes[0,1].set_title('Eficiencia de Políticas', fontweight='bold')
    axes[0,1].set_xlabel('Episodio')
    axes[0,1].set_ylabel('Duración del Episodio')
    axes[0,1].legend()
    axes[0,1].grid(True, alpha=0.3)

    # 3. Evolución de exploración
    axes[0,2].plot(episodios_q, resultados_qlearning['valores_epsilon'],
                  color='blue', linewidth=2, label='Q-Learning')
    axes[0,2].plot(episodios_dqn, resultados_dqn['valores_epsilon'],
                  color='red', linewidth=2, label='DQN')
    axes[0,2].set_title('Decaimiento de Exploración', fontweight='bold')
    axes[0,2].set_xlabel('Episodio')
    axes[0,2].set_ylabel('Epsilon')
    axes[0,2].legend()
    axes[0,2].grid(True, alpha=0.3)

    # 4. Convergencia Q-Learning
    if resultados_qlearning['errores_td_promedio']:
        axes[1,0].plot(episodios_q, resultados_qlearning['errores_td_promedio'],
                      color='blue', alpha=0.7)
        axes[1,0].set_title('Convergencia Q-Learning (Errores TD)', fontweight='bold')
        axes[1,0].set_xlabel('Episodio')
        axes[1,0].set_ylabel('Error TD Promedio')
        axes[1,0].grid(True, alpha=0.3)

    # 5. Convergencia DQN
    if resultados_dqn['perdidas_entrenamiento']:
        axes[1,1].plot(resultados_dqn['perdidas_entrenamiento'], color='red', alpha=0.7)
        axes[1,1].set_title('Convergencia DQN (Pérdida MSE)', fontweight='bold')
        axes[1,1].set_xlabel('Episodio')
        axes[1,1].set_ylabel('Pérdida de Entrenamiento')
        axes[1,1].grid(True, alpha=0.3)

    # 6. Distribuciones de rendimiento - IMPLEMENTACIÓN MEJORADA
    axes[1,2].remove()  # Eliminar el subplot original


    # Crear subplots personalizados para distribuciones separadas
    gs_dist = fig.add_gridspec(2, 2, left=0.68, right=0.98, top=0.42, bottom=0.05,
                          hspace=0.4, wspace=0.1)

    # Subplot superior: Q-Learning
    ax_q_dist = fig.add_subplot(gs_dist[0, :])
    ax_q_dist.hist(resultados_qlearning['recompensas_episodio'], bins=7,
                   alpha=0.8, color='blue', density=True, edgecolor='navy')
    ax_q_dist.set_title('Q-Learning (GridWorld)', fontweight='bold', fontsize=11)
    ax_q_dist.set_ylabel('Densidad')
    ax_q_dist.grid(True, alpha=0.3)

    # Estadísticas para Q-Learning
    media_q = np.mean(resultados_qlearning['recompensas_episodio'])
    ax_q_dist.axvline(media_q, color='darkblue', linestyle='--', linewidth=2)
    ax_q_dist.text(0.7, 0.8, f'Media: {media_q:.2f}',
                   transform=ax_q_dist.transAxes, fontsize=10,
                   bbox=dict(boxstyle="round,pad=0.3", facecolor="lightblue", alpha=0.8))

    # Subplot inferior: DQN
    ax_dqn_dist = fig.add_subplot(gs_dist[1, :])
    ax_dqn_dist.hist(resultados_dqn['recompensas_episodio'], bins=25,
                     alpha=0.8, color='red', density=True, edgecolor='darkred')
    ax_dqn_dist.set_title('DQN (CartPole)', fontweight='bold', fontsize=11)
    ax_dqn_dist.set_xlabel('Recompensa por Episodio')
    ax_dqn_dist.set_ylabel('Densidad')
    ax_dqn_dist.grid(True, alpha=0.3)

    # Estadísticas para DQN
    media_dqn = np.mean(resultados_dqn['recompensas_episodio'])
    ax_dqn_dist.axvline(media_dqn, color='darkred', linestyle='--', linewidth=2)
    ax_dqn_dist.text(0.7, 0.8, f'Media: {media_dqn:.1f}',
                     transform=ax_dqn_dist.transAxes, fontsize=10,
                     bbox=dict(boxstyle="round,pad=0.3", facecolor="lightcoral", alpha=0.8))

    # Layout final optimizado
    plt.tight_layout(rect=[0, 0, 1, 0.94])
    plt.suptitle('Análisis Comparativo: Q-Learning Tabular vs Deep Q-Networks',
                fontsize=16, fontweight='bold', y=0.96)
    plt.show()

# Generar análisis comparativo
visualizar_comparacion_algoritmos(resultados_entrenamiento, resultados_dqn)

print("\n✅ Módulo 8B completado - Análisis comparativo finalizado")

# ============================================================================
# EVALUACIÓN FINAL DE AMBOS AGENTES
# ============================================================================

print(f"\n🎯 EVALUACIÓN COMPARATIVA FINAL")

def evaluar_agente_qlearning(env, agente, n_evaluaciones: int = 100) -> Dict:
    """Evalúa rendimiento del agente Q-Learning entrenado."""

    recompensas = []
    longitudes = []
    tasa_exito = 0

    for evaluacion in range(n_evaluaciones):
        estado = env.reset()
        recompensa_total = 0
        pasos = 0

        while True:
            accion = agente.seleccionar_accion(estado, modo_entrenamiento=False)
            estado, recompensa, terminado, _ = env.step(accion)
            recompensa_total += recompensa
            pasos += 1

            if terminado or pasos > 50:
                if recompensa > 0:  # Éxito en GridWorld
                    tasa_exito += 1
                break

        recompensas.append(recompensa_total)
        longitudes.append(pasos)

    return {
        'recompensa_promedio': np.mean(recompensas),
        'std_recompensa': np.std(recompensas),
        'longitud_promedio': np.mean(longitudes),
        'std_longitud': np.std(longitudes),
        'tasa_exito': tasa_exito / n_evaluaciones
    }

def evaluar_agente_dqn(env, agente, n_evaluaciones: int = 100) -> Dict:
    """Evalúa rendimiento del agente DQN entrenado."""

    recompensas = []
    longitudes = []
    umbral_exito = 195  # Umbral estándar para CartPole

    for evaluacion in range(n_evaluaciones):
        if tipo_gym == 'gymnasium':
            estado, _ = env.reset()
        else:
            estado = env.reset()

        estado = np.array(estado, dtype=np.float32)
        recompensa_total = 0
        pasos = 0

        while True:
            accion = agente.actuar(estado, modo_entrenamiento=False)

            if tipo_gym == 'gymnasium':
                estado, recompensa, terminado, truncado, _ = env.step(accion)
                terminado = terminado or truncado
            else:
                estado, recompensa, terminado, _ = env.step(accion)

            estado = np.array(estado, dtype=np.float32)
            recompensa_total += recompensa
            pasos += 1

            if terminado or pasos > 500:
                break

        recompensas.append(recompensa_total)
        longitudes.append(pasos)

    tasa_exito = np.mean([r >= umbral_exito for r in recompensas])

    return {
        'recompensa_promedio': np.mean(recompensas),
        'std_recompensa': np.std(recompensas),
        'longitud_promedio': np.mean(longitudes),
        'std_longitud': np.std(longitudes),
        'tasa_exito': tasa_exito
    }

# Evaluaciones finales
print(f"\n📊 Evaluando Q-Learning en GridWorld...")
eval_qlearning = evaluar_agente_qlearning(env_educativo, agente_qlearning)

print(f"\n📊 Evaluando DQN en CartPole...")
eval_dqn = evaluar_agente_dqn(env_cartpole, agente_dqn)

# Mostrar resultados comparativos
print(f"\n" + "="*70)
print(f"📋 RESULTADOS COMPARATIVOS FINALES")
print(f"="*70)

print(f"\n🎯 Q-LEARNING TABULAR (GridWorld 5×6):")
print(f"   • Recompensa promedio: {eval_qlearning['recompensa_promedio']:.3f} ± {eval_qlearning['std_recompensa']:.3f}")
print(f"   • Longitud promedio: {eval_qlearning['longitud_promedio']:.1f} ± {eval_qlearning['std_longitud']:.1f} pasos")
print(f"   • Tasa de éxito: {eval_qlearning['tasa_exito']:.1%}")
print(f"   • Espacio de estados: Discreto, 30 estados")
print(f"   • Memoria requerida: ~30×4 = 120 valores Q")

print(f"\n🧠 DEEP Q-NETWORK (CartPole):")
print(f"   • Recompensa promedio: {eval_dqn['recompensa_promedio']:.1f} ± {eval_dqn['std_recompensa']:.1f}")
print(f"   • Longitud promedio: {eval_dqn['longitud_promedio']:.1f} ± {eval_dqn['std_longitud']:.1f} pasos")
print(f"   • Tasa de éxito (≥195): {eval_dqn['tasa_exito']:.1%}")
print(f"   • Espacio de estados: Continuo, 4 dimensiones")
print(f"   • Memoria requerida: {sum(p.numel() for p in agente_dqn.red_q.parameters()):,} parámetros")

print("\n✅ Módulo 8B completado - Análisis comparativo finalizado")

# ============================================================================
# SÍNTESIS FINAL Y CONCLUSIONES PEDAGÓGICAS
# ============================================================================

"""
## SÍNTESIS FINAL: REFLEXIONES SOBRE EL APRENDIZAJE POR REFUERZO

**OBJETIVO PEDAGÓGICO:**
Consolidar todo el aprendizaje en una síntesis coherente que permita a los
estudiantes comprender el panorama completo del campo y las direcciones
futuras de investigación.
"""

print("\n" + "="*70)
print("🎓 SÍNTESIS FINAL: PANORAMA DEL APRENDIZAJE POR REFUERZO")
print("="*70)

print("""
🔬 HALLAZGOS FUNDAMENTALES DE NUESTRO EXPERIMENTO:

1. ESCALABILIDAD Y APLICABILIDAD:

   Q-Learning Tabular → Óptimo para:
   • Espacios de estados discretos pequeños (< 10⁴ estados)
   • Problemas donde la interpretabilidad es crucial
   • Situaciones con garantías teóricas de convergencia
   • Recursos computacionales limitados

   Deep Q-Networks → Óptimo para:
   • Espacios de estados continuos o muy grandes
   • Problemas con representaciones de alta dimensionalidad
   • Necesidad de generalización a estados no visitados
   • Disponibilidad de recursos computacionales significativos

2. TRADE-OFFS OBSERVADOS:

   Interpretabilidad vs Escalabilidad:
   • Tabular: Cada Q(s,a) es interpretable pero limitado por |S|×|A|
   • DQN: Escalable pero función Q implícita en parámetros de red

   Garantías Teóricas vs Flexibilidad Práctica:
   • Tabular: Convergencia garantizada bajo condiciones apropiadas
   • DQN: Mayor flexibilidad pero convergencia no garantizada

   Eficiencia Muestral vs Capacidad Expresiva:
   • Tabular: Eficiente en problemas simples, cada experiencia actualiza solo una entrada
   • DQN: Menos eficiente muestralmente pero captura patrones complejos

3. INNOVACIONES ARQUITECTÓNICAS CLAVE:

   Experience Replay:
   • Rompe correlaciones temporales → estabilidad de entrenamiento
   • Reutilización de experiencias → eficiencia muestral mejorada

   Target Networks:
   • Targets estables → reduce varianza en actualización de parámetros
   • Actualización periódica → balance entre estabilidad y adaptabilidad

🌟 INSIGHTS PEDAGÓGICOS EMERGENTES:

• El aprendizaje por refuerzo unifica conceptos de optimización, probabilidad,
  y aproximación funcional en un marco conceptual elegante

• La transición tabular→funcional ilustra perfectamente el trade-off
  interpretabilidad-escalabilidad central en machine learning

• Experience replay demuestra cómo las innovaciones algorítmicas pueden
  resolver limitaciones fundamentales (correlación temporal)

• El balance exploración-explotación representa un meta-principio que
  trasciende el RL y se aplica a cualquier proceso de optimización secuencial

🔮 DIRECCIONES FUTURAS PROMETEDORAS:

1. MÉTODOS DE GRADIENTE DE POLÍTICA:
   • REINFORCE, Actor-Critic, PPO, SAC
   • Optimización directa de políticas vs aproximación de funciones de valor

2. APRENDIZAJE BASADO EN MODELOS:
   • Model-Predictive Control + Deep Learning
   • Planificación en espacios latentes aprendidos

3. APRENDIZAJE POR REFUERZO JERÁRQUICO:
   • Descomposición de problemas complejos en subproblemas
   • Transferencia de conocimiento entre tareas relacionadas

4. RL MULTI-AGENTE:
   • Coordinación y competencia entre agentes inteligentes
   • Emergencia de comportamientos sociales complejos

🎯 COMPETENCIAS DESARROLLADAS:

✓ Comprensión profunda de MDPs como formalización matemática
✓ Implementación práctica de algoritmos fundamentales de RL
✓ Análisis crítico de trade-offs algorítmicos y arquitectónicos
✓ Capacidad de seleccionar métodos apropiados según características del problema
✓ Habilidades de experimentación y análisis de resultados en ML
✓ Visión panorámica del campo con apertura hacia investigación avanzada

📚 RECURSOS PARA PROFUNDIZACIÓN CONTINUA:

• Libros fundamentales:
  - Sutton & Barto: "Reinforcement Learning: An Introduction" (2018)
  - Bertsekas: "Dynamic Programming and Optimal Control" (2017)

• Artículos seminales:
  - Mnih et al.: "Human-level control through deep RL" (Nature, 2015)
  - Schulman et al.: "Proximal Policy Optimization Algorithms" (2017)
  - Haarnoja et al.: "Soft Actor-Critic" (2018)

• Recursos prácticos:
  - OpenAI Spinning Up: Implementaciones educativas de algoritmos modernos
  - Stable Baselines3: Biblioteca de algoritmos de RL bien documentada
  - Papers With Code: Tracking del estado del arte en RL

🏆 MENSAJE FINAL:

El aprendizaje por refuerzo representa una de las fronteras más emocionantes
de la inteligencia artificial, donde la elegancia matemática se encuentra
con aplicaciones transformadoras del mundo real. Desde robots que aprenden
a caminar hasta sistemas que dominan juegos complejos, RL ofrece un paradigma
poderoso para crear agentes verdaderamente autónomos.

Su viaje en este campo apenas comienza. Los fundamentos sólidos que han
construido hoy les proporcionan las herramientas conceptuales y prácticas
necesarias para contribuir a esta disciplina en rápida evolución.

¡El futuro de la IA inteligente está en sus manos!
""")

print("\n🎉 ¡FELICITACIONES!")
print("✅ Han completado exitosamente el recorrido comprehensivo por el aprendizaje por refuerzo")
print("🔬 Desde los fundamentos matemáticos hasta las implementaciones más avanzadas")
print("🌟 Están preparados para abordar problemas reales de RL y contribuir al campo")

# Cerrar entornos apropiadamente
env_cartpole.close()

print("\n🎓 FIN DEL CUADERNO EDUCATIVO")
print("📧 Para consultas adicionales o profundización, contacten al instructor")